stages:
  - build

flutter-build:
  image: cirrusci/flutter:stable
  stage: build
  when: manual
  before_script:
    - flutter packages get
    - flutter clean
  script:
    - flutter doctor --android-licenses
    - flutter build apk --release --no-sound-null-safety
  artifacts:
    paths:
      - "**/**/**/**/**/**/app-release.apk"